# 2023-05-15(월) TIL

# 키워드
- Exception
- Checked Exception / Unchecked Exception
- 예외 처리 방식 (try-catch-finally)
- 다중 catch 블록
  - 주의점
- catch 순서
- throws
- 자바 7의 multi-catch

## Exception
- 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인한 오류
  
### Exception의 종류 3가지
1. Error
2. Exception 
   2-1. Checked Exception
   2-2. Unchecked Exception (Runtime Exception)


### 1. Error
- 프로그램 밖에서 발생한 예외로, 발생 시 프로세스에 영향을 줘서 프로그램이 제대로 동작하지 못한다
- ex) 서버 디스크 고장, 메인보드 맛이 감

### 2. Exception
- 프로그램 안에서 발생한 예외, 발생 시 쓰레드에만 영향을 줘서 프로그램을 계속 실행할 수는 있다
- Checked Exception / Unchecked Exception : 구별 방법은 `RuntimeException` 을 상속했는지 아닌지 여부를 보고 구별한다
- 자바에서는 예외를 클래스로 관리한다
  - JVM은 프로그램을 실행하는 도중에 예외가 발생하면 해당 예외 클래스로 객체를 생성한다
  - 이후 예외 처리 코드에서 생성한 예외 객체를 이용한다
  - 모든 예외 클래스들은 `java.lang.Exception` 을 상속 받는다

### 2-1. Checked Exception (일반 예외)
- `java.lang.RuntimeException` 을 상속하지 않는 예외
- 컴파일러 체크 예외라고도 한다 = `Compile Time Exception`
- 자바 소스를 컴파일 하는 과정에서 예외 처리 코드가 필요한지 검사한다
- 예외 처리 코드가 없다면 컴파일 오류를 발생시킨다

### 2-2. Runtime Exception (Unchecked Excpetion)
- `java.lang.RuntimeException` 을 상속하는 예외
- 컴파일 하는 과정에서 예외 처리 코드를 검사하지 않는 예외
- 개발자의 경험에 의해서 예외 처리 코드를 삽입해야 한다

## 예외 처리 방식
- 프로그램에서 예외가 발생했을 때, 프로그램의 갑작스러운 종료를 막고, 정상 실행을 유지할 수 있도록 처리하는 코드

### try - catch - finally
1. try
   - 예외 발생 가능 코드가 위치한다
   - `try-catch` 는 짝이다
2. catch
   - 예외 발생 시 catch 블록으로 이동한다
   - `try` 에서 예외 발생 없이 정상 실행 --> `catch` 는 실행되지 않음, `finally` 만 실행된다
   - `try` 에서 예외 발생 --> 즉시 실행을 멈추고, `catch` 블록으로 이동해서 예외 처리 코드를 실행하고, `finally` 코드를 실행한다
3. finally
   - 옵션으로, 생략 가능하다
   - 예외 발생 여부와 관계 없이, 항상 실행할 내용이 있으면 `finally` 에 작성하면 된다 (`finally` 는 항상 실행된다)


## 다중 catch
- 다양한 종류의 예외를 발생되는 예외 별로 예외 처리 코드를 다르게하기 위해 다중 catch 블록을 작성한다
- `catch` 블록의 예외 클래스 타입 = `try` 블록에서 발생된 예외의 종류 (`try` 에서 예외 발생 시, `catch` 블록을 실행한다)
- `catch` 블록이 여러 개라고 해도 단 하나의 `catch` 만 실행된다 (`try` 에서 동시다발적으로 예외가 발생하지는 않는다, 하나의 예외가 발생하면 즉시 실행을 멈추고 catch로 간다)

### 주의점
- 상위 예외 클래스가 하위 예외 클래스보다 아래 catch 블록에 위치해야 한다
  - 왜?
    - try에서 예외가 발생하면, 예외를 처리해 줄 catch 블록은 위에서부터 차례대로 검색되기 때문이다


## Multi Catch
- 자바 7부터 catch 블록에서 여러 개의 예외를 처리할 수 있도록 함
```java
try {
	// ArrayIndexOutOfBoundsException 또는 NumberFormatException 발생

	// 다른 Exception 발생
} catch (ArrayIndexOutOfBoundsException | NumberFormatException e) {
	예외 처리 1
} catch (Exception e) {
	예외 처리 2
}
```

## 예외 떠넘기기 (throws)
- 경우에 따라 메소드를 호출한 곳으로 예외를 떠넘길 수도 있다
- `throws`

### `throws`
- 메소드 선언부 끝에 작성되어 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역할
```java
리턴타입 메소드명(매개변수, ...) throws 예외클래스 1, 예외 클래스2 , ... {
}
```
- 떠넘긴 곳에서 (메소드를 호출한 곳에서) 예외를 처리해야 한다
  - 그렇지 않으면 **컴파일 오류**

- main 메소드에서도 예외를 떠넘기면 JVM이 예외 처리를 한다
  - 콘솔 출력하는 것으로 예외 처리한다

![exception_hierarchy] (https://github.com/yeGenieee/java-live-study/blob/main/image/exception_hierarchy.png)

## 자동 리소스 닫기 (`try-with-resources`)
- 자바 7에서 추가된 사항, 예외 발생 여부와 상관없이 사용했던 리소스 객체 (입출력 스트림, 서버 소켓, 소켓... 등) 의 `close()` 메소드를 호출해서 안전하게 리소스를 닫는다

```java
try (FileInputStream fis = new FileInputStream("file.txt")) {
	...
} catch (IOException e) {
  ...
}
```
- 명시적으로 close() 를 호출한 곳이 없다
- try 블록이 정상적으로 실행을 완료했거나 도중에 예외가 발생하게 되면, 자동으로 FileInputStream의 close() 메소드가 호출된다
- try 에서 예외가 발생하면 우선 close()로 리소스를 닫고 catch 블록을 실행한다
- `try-with-resources` 를 사용하기 위해서는 리소스 객체는 `java.lang.AutoClosable` 인터페이스를 구현하고 있어야 한다
  - 왜?
    - `java.lang.AutoClosable` 에는 `close()` 메소드가 정의되어 있어서, `try-with-resources` 가 close() 메소드를 자동으로 호출한다


